import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'es', 'fr', 'ar', 'ko'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? frText = '',
    String? arText = '',
    String? koText = '',
  }) =>
      [enText, esText, frText, arText, koText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // insights
  {
    'xst778f9': {
      'en': 'Week',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2umem4zt': {
      'en': 'My Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2xluclyn': {
      'en': '\$ 1,747.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7tsu3264': {
      'en': '-11.8%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3bic3o9u': {
      'en': 'from last week',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a87d4r99': {
      'en': 'In thousands',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'q6s8q7jc': {
      'en': 'Month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xqib5b2x': {
      'en': 'My Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uht4l99g': {
      'en': '\$ 35,747.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wzh4gvvp': {
      'en': '+10.8%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gcxcac2u': {
      'en': 'from last year',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ftrt2w0l': {
      'en': 'In thousands',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kz4wd659': {
      'en': 'Top Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1hmvgrl1': {
      'en': 'All',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '0v9xfpou': {
      'en': 'Brand',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'cny18nme': {
      'en': 'Contact',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hojow3oq': {
      'en': 'All',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fqb62kz9': {
      'en': 'Search for an item...',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l133habz': {
      'en': 'Grocery store',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fl686svi': {
      'en': '-712.99',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jbg9ycnh': {
      'en': 'Year',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8o3yw9k8': {
      'en': 'My Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'x2ixjpuh': {
      'en': '\$ 48,327.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7hny9lln': {
      'en': '+4.8%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3crarklp': {
      'en': 'from last two years',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'aumny49y': {
      'en': 'In thousands',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hqvkxkbc': {
      'en': 'Top Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '08i19ccj': {
      'en': 'All',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p3jwjw8s': {
      'en': 'Brand',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'y540lvup': {
      'en': 'Contact',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4lfiyb6b': {
      'en': 'All',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '31c7hpte': {
      'en': 'Search for an item...',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5qjcy29p': {
      'en': 'Grocery store',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '69n1d1pa': {
      'en': '-712.99',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qpvxb5cb': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bh7vyslg': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'w1a40piw': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qow31cgv': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'n0jzwa37': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6ze2e8xh': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kw4zqzxq': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bxlwef3z': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'phgpmfax': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pod0qle7': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zretvwt8': {
      'en': 'Stats',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // profile
  {
    'y1rfrewm': {
      'en': 'Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5rwohnco': {
      'en': 'Edit Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'seyrz8px': {
      'en': 'My Account',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ollmhdyr': {
      'en': 'My QRIS',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'oyg2oool': {
      'en': 'Address',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jvnr9v5c': {
      'en': 'Settings',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'owvg6ihf': {
      'en': 'Help Center',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xoh9uvgk': {
      'en': 'Contact',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dtw4q06h': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '86kmbr80': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'loqcsgqa': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kzut3p1r': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b8p2hnz7': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'frjjwnj1': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'c4yvvr2d': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gc66jucv': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'tmm70lyu': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7molcpo6': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // editMyAccount
  {
    '88vfnuus': {
      'en': 'My Account',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'o2rvdm8o': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'r34f4hdu': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    's8yhoul6': {
      'en': 'First Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lj3orsoj': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '0eqs2gpc': {
      'en': 'Last Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'mjbwa06e': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b21qggzp': {
      'en': 'Phone Number',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '45x5rfce': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gafaelwz': {
      'en': 'Confirm Changes',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2yoqzlfk': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // sign_up
  {
    'epsc8k6p': {
      'en': 'Sign Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'cl4kez19': {
      'en': 'Create account today!',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'd4986y12': {
      'en': 'First name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'scfeohz2': {
      'en': 'first name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'culox81f': {
      'en': 'last name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2od00li2': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7red3pd8': {
      'en': 'enter a valid email address',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ygww092v': {
      'en': 'Phone Number',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ih12q2qp': {
      'en': 'enter your mobile number here',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ywn9va4r': {
      'en': 'Password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bmaraczb': {
      'en': 'create a password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dygcyj7q': {
      'en': 'Confirm Password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qchsj1u3': {
      'en': 'confirm password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4naf3d43': {
      'en': 'I agree to the Paavya ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rg8fljl9': {
      'en': 'Privacy Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ui2rbktv': {
      'en': ' and ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '80vhhy7w': {
      'en': 'Terms of Service',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bft2dbyk': {
      'en': 'Sign Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'u8ohmbyj': {
      'en': 'Already have an account?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ac3mqnxo': {
      'en': ' Login',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'se2kc3f6': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Forgotpassword1
  {
    'i14kjulb': {
      'en': 'Forgot password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gzzk7d5o': {
      'en': 'Select verification method and we will\nsend a verification code',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'd2zwc682': {
      'en': 'Send to email ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'v870cbe0': {
      'en': 'Send to SMS   ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1t5t7pf2': {
      'en': 'Continue',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '96mv4w5i': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // AccountVerified
  {
    'osoew2q1': {
      'en': 'Account Verified',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ls0e3dyj': {
      'en':
          'Your account has been verified\nsuccessfully, now let\'s enjoy\nPaavya features!',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3c9s0d3v': {
      'en': 'Get Started',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'snm5d9p5': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Settings
  {
    '8orzrhw3': {
      'en': 'General',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ds8ypecm': {
      'en': 'Language',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k7vg9fai': {
      'en': 'English',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3mcwx0yd': {
      'en': 'Reset Password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'yu034x4u': {
      'en': 'Security',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z9f7tfj5': {
      'en': 'Notifications',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4eak0bff': {
      'en': 'Biometric',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'r5qnllxo': {
      'en': 'Enable finderprint scan and Face ID',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a3z7tnno': {
      'en': 'Please authenticate to login',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p5lwokcz': {
      'en': 'Dark Mode',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'blu2rw4e': {
      'en': 'Switch between light & dark mode',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'm8mvbcxg': {
      'en': 'Privacy Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zg3po1kn': {
      'en': 'Settings',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a90lml67': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Address
  {
    'vvre487w': {
      'en': 'Your Location',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '0v87oghw': {
      'en': 'Current Location',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '81o4wphq': {
      'en': '3328 Lake Heights Ct.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'h9tym5kv': {
      'en': 'Dacula, GA 30019',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p30nxu6y': {
      'en': 'Change',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9i4945fy': {
      'en': 'Settings',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5icr2nvc': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // myAccounts
  {
    'n4nea7wp': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9mgfd52p': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8r3hf75a': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'h52nye57': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pojadz68': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kcy5cu0v': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b5h2xm4x': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kv23x4e3': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'os38bwu7': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1cs2ae7g': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8xmuhjz6': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // profileDetails
  {
    '89vseji4': {
      'en': 'Profile Details',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ldc8aspy': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '560xbyi3': {
      'en': 'First & Last Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'u300gtcr': {
      'en': 'Phone Number',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9igt02o6': {
      'en': 'Log out\n',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'cck9ilrh': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // topup_success
  {
    'ntw8vlln': {
      'en': 'Top Up Successsful',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'u4ckk9hs': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xnnaye1z': {
      'en': 'Transction ID:',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'f4iwdaqo': {
      'en': 'AO2512273019231221662',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jty5z5db': {
      'en': 'Back to home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'm908w2bk': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // create_budget
  {
    'ebv6spsf': {
      'en': 'Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l8y6fl99': {
      'en': 'Item title you want to budget',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kvkwid8r': {
      'en': 'Fast Food',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'op57dir0': {
      'en': 'Restaurant',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'vg83u7gm': {
      'en': 'Groceries',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wjj2xp7p': {
      'en': 'Retail',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1rb0ufrw': {
      'en': 'Gas',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'j9yfa7ln': {
      'en': 'Other',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ahy4c3wk': {
      'en': 'Budget',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'yritc6xs': {
      'en': 'ex. 1450.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '63ikyomm': {
      'en': 'Frequency',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pisi8rnn': {
      'en': 'Monthly',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ycxnvqa7': {
      'en': 'Annually',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ichkpid0': {
      'en': 'One-Time',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zzp0wx23': {
      'en': 'Select One',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ydxkmckm': {
      'en': 'Search for an item...',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'eystmejx': {
      'en': 'Details',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nh6c3how': {
      'en': 'enter details for your budget item',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zcm9witv': {
      'en': 'Save',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'tiuaukv7': {
      'en': 'Create Budget',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'y2rzrlze': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // cardDetails
  {
    '9suq6297': {
      'en': 'Card Settings',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a3xad9a3': {
      'en': 'Top Up money',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a0nzru2c': {
      'en': 'My budget',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kwgkomfd': {
      'en': 'Set limits',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gygt8460': {
      'en': 'Lock card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'u5lctjqm': {
      'en': 'Card Details',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    's76tgwx8': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // addNewcard
  {
    'llk3iiwd': {
      'en': 'Cardholder Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qrl0nv90': {
      'en': 'enter name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'oy2wftdj': {
      'en': 'Card Nickname',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fasgsl4w': {
      'en': 'create a nickname',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ub97recy': {
      'en': 'Card Number',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rbqjxez8': {
      'en': 'enter your 16 digit card number ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xan31itz': {
      'en': 'Expiry Date',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2k5m3cz9': {
      'en': 'ex. 08/23',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    's2y9t5eh': {
      'en': 'CVV',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jfpn7gz7': {
      'en': 'ex. 992',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jjsky8z9': {
      'en': 'Zip Code',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ynfua00o': {
      'en': 'enter your zip code',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fmih6h0g': {
      'en': 'Add Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kq48oepr': {
      'en': 'Add New Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fx6vhppw': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // onboarding_flow
  {
    '6nx06l2j': {
      'en': 'Mobile banking \nyou\'ll need',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kgpvxh45': {
      'en': 'A wallet in your pocket to spend\nyour money way smarter.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'arrj80k3': {
      'en': 'Next',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8l2h91sf': {
      'en': 'Manage your money \nwisely',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gvmlz8kh': {
      'en':
          'Track your money flows, balance, and\n everyday transactions on the go.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ftd5kuov': {
      'en': 'Next',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6qz2vu89': {
      'en': 'Send money with \nno problem',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'sek7m4lt': {
      'en': 'Send money to your friends and families \nwith no worries.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '31eff7sr': {
      'en': 'Next',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ytee8a2a': {
      'en': 'Multiple cards in one\napplication',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nzubaare': {
      'en': 'Manage your cards so you can use \nthem without switching apps.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'stte8foi': {
      'en': 'Next',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'e31ergy5': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Onboarding2
  {
    '19ffw4rw': {
      'en': 'Before you start',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fw7otecr': {
      'en':
          'Each section will need to be filled, it \nonly takes a couple of minutes!.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jdhhz1g8': {
      'en': 'About you',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'espg4gam': {
      'en': 'Your citizenship and \nemployment status.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rr92v233': {
      'en': 'Your finances',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z91evdmq': {
      'en': 'Your income and committed \nspending.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ieehe48i': {
      'en': 'Your account',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l83kgssx': {
      'en': 'How you’ll plan your Paavya \naccount.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '071d24o1': {
      'en': 'Your identity',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4bygnrc2': {
      'en': 'Checking to make sure your \nID and you match.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'sgy566k9': {
      'en': 'We\'ll always keep information \nsecure and confidential.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dv068xu9': {
      'en': 'Get Started',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lt6yifkd': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // dashboard
  {
    '065jr86m': {
      'en': 'Good day to you!',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ce0yzidh': {
      'en': 'It\'s,',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4hbef61u': {
      'en': 'Nov 14',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9ofxfya6': {
      'en': 'Trey Banks',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wvn067u0': {
      'en': 'Current Balance',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rv7uh2jv': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hx0tromy': {
      'en': 'as of about',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jytgx1vf': {
      'en': '2 hours ago ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z86vdtog': {
      'en': 'sync',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nkz0dfi2': {
      'en': 'Savings Plan',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2jriaeis': {
      'en': '33%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b295e3xx': {
      'en': 'View More',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'g6wx5xi4': {
      'en': 'Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8zbg315q': {
      'en': '87%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5iou3yy9': {
      'en': '\$120 more spent than last month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gwced6yk': {
      'en': 'Quick Actions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pwbqduvo': {
      'en': 'Top Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l0qe62jg': {
      'en': 'Transfer',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gjdjwk7o': {
      'en': 'Withdraw',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kci46lab': {
      'en': 'Bill Pay',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uruc9i0e': {
      'en': 'Recent Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'swa4q2li': {
      'en': 'View all',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k7y1405e': {
      'en': 'All',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6862hoit': {
      'en': 'Income',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bph1y913': {
      'en': 'Expenses',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pa46jw30': {
      'en': 'My Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4zp9sm6x': {
      'en': '\$ 1,747.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ziykaoq4': {
      'en': '-11.8%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8on4mj96': {
      'en': 'from last week',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'mn92pyhl': {
      'en': 'See more',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uiyz9jin': {
      'en': 'In thousands',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8l1fyd9a': {
      'en': 'Upcoming Bills',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'g6au2l9e': {
      'en': 'View all',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lhgqwbc7': {
      'en': 'Monthly Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'clq7k3i9': {
      'en': 'View all',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'unsah9xm': {
      'en': 'Saving Goals',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1ocv0r2r': {
      'en': 'Create new',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'he8teno9': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6m1scxo5': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b3dc6edt': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8ffz7tz0': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'myft69oh': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'y2c2h8ww': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p8o2qsm1': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6qpm1grr': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9nn29u0x': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hj32600e': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // allTransactions
  {
    'ydw972y1': {
      'en': 'search transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k78a7s93': {
      'en': 'Jun',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1yjdglqf': {
      'en': 'Jan',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '15iv6edu': {
      'en': 'Feb',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'g4ekr9m6': {
      'en': 'Mar',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2k1vwamn': {
      'en': 'Apr',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8npkk9j1': {
      'en': 'May',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4mwoth38': {
      'en': 'Jun',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lp7goyon': {
      'en': 'Jul',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kdvyey56': {
      'en': 'Aug',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'g9z8kmh8': {
      'en': 'Sept',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ea7qc7nz': {
      'en': 'Oct',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p3npioxu': {
      'en': 'Nov',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6nd2rqht': {
      'en': 'Dec',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '0sou7gg6': {
      'en': 'Please select...',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'c89kxswt': {
      'en': 'Search for an item...',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qmiv1akr': {
      'en': 'Total Spending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ukh92d0b': {
      'en': 'Latest Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '47jvy4wd': {
      'en': 'JoeMoe Coffee',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '718i29v8': {
      'en': 'Paid ending: **** 2192',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6njpx0xz': {
      'en': '\$50.21',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'o879nw18': {
      'en': 'All Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5a8yawwb': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ymdhv35a': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nsj32vab': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '94ecs2mg': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '844pvfi9': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'x7iq21fg': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k0liu68q': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jlz1fdcs': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'c9as9lx3': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'h777z8p7': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // topup_failed
  {
    'rnwxtq6r': {
      'en': 'Top Up failed',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xqy55kql': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9v25ozyp': {
      'en': 'Go back to try again',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z8u0rb4c': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // withdraw_success
  {
    'kxca5dh7': {
      'en': 'Withdraw Successsful',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'aaad7jst': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l13ebq63': {
      'en': 'Transction ID:',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ibqvfcx8': {
      'en': 'AO2512273019231221662',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'f53lgry0': {
      'en': 'Back to home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pzhnjytn': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // withdraw_failed
  {
    '8t2hhn5a': {
      'en': 'Withdraw failed',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uae1exl0': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '54ktwueo': {
      'en': 'Go back to try again',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'occxs8f3': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // transfer_success
  {
    'gk34cuar': {
      'en': 'Transfer Successsful',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '806qdwc7': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'iife5pl4': {
      'en': 'Transction ID:',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hi75in3w': {
      'en': 'AO2512273019231221662',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rao4dqh1': {
      'en': 'Back to home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k9g3hiya': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // transfer_failed
  {
    'bvsotzlu': {
      'en': 'Transfer failed',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rdfl1xge': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5l2i76ci': {
      'en': 'Go back to try again',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zsjw0je6': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // PrivacyPolicy
  {
    'd6r2xqfj': {
      'en':
          'Protecting your private information is our priority. This Statement of Privacy applies to Paavya mobile, and Paavya LLC and governs data collection and usage. For the purposes of this Privacy Policy, unless otherwise noted, all references to Paavya LLC include www.paavya.com and Paavya. The Paavya application is a financial information application. By using the Paavya application, you consent to the data practices described in this statement.\nCollection of your Personal Information\nIn order to better provide you with products and services offered, Paavya may collect personally identifiable information, such as your:\n- First and Last Name\n- Mailing Address\n- E-mail Address\n- Phone Number\n\nIf you purchase Paavya\'s products and services, we collect billing and credit card information. This information is used to complete the purchase transaction.\nPaavya may also collect anonymous demographic information, which is not unique to you, such as your:\n- Household Income\n\nWe do not collect any personal information about you unless you voluntarily provide it to us. However, you may be required to provide certain personal information to us when you elect to use certain products or services. These may include: (a) registering for an account; (b) entering a sweepstakes or contest sponsored by us or one of our partners; (c) signing up for special offers from selected third parties; (d) sending us an email message; (e) submitting your credit card or other payment information when ordering and purchasing products and services. To wit, we will use your information for, but not limited to, communicating with you in relation to services and/or products you have requested from us. We also may gather additional personal or non-personal information in the future.\nUse of your Personal Information\nPaavya collects and uses your personal information to operate and deliver the services you have requested.\nPaavya may also use your personally identifiable information to inform you of other products or services available from Paavya and its affiliates.\nSharing Information with Third Parties\nPaavya does not sell, rent or lease its customer lists to third parties.\nThis is a RocketLawyer.com document.\n Paavya may share data with trusted partners to help perform statistical analysis, send you email or postal mail, provide customer support, or arrange for deliveries. All such third parties are prohibited from using your personal information except to provide these services to Paavya, and they are required to maintain the confidentiality of your information.\n\nPaavya may disclose your personal information, without notice, if required to do so by law or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on Paavya or the site; (b) protect and defend the rights or property of Paavya; and/or (c) act under exigent circumstances to protect the personal safety of users of Paavya, or the public.\nRight to Deletion\nSubject to certain exceptions set out below, on receipt of a verifiable request from you, we will:\n• Delete your personal information from our records; and\n• Direct any service providers to delete your personal information from their records.\n\nPlease note that we may not be able to comply with requests to delete your personal information if it is necessary to:\n• Complete the transaction for which the personal information was collected, fulfill the terms of a written warranty or product recall conducted in accordance with federal law, provide a good or service requested by you, or reasonably anticipated within the context of our ongoing business relationship with you, or otherwise perform a contract between you and us;\n• Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity; or prosecute those responsible for that activity;\n• Debug to identify and repair errors that impair existing intended functionality;\n• Exercise free speech, ensure the right of another consumer to exercise his or her right\nof free speech, or exercise another right provided for by law;\n• Comply with the California Electronic Communications Privacy Act;\n• Engage in public or peer-reviewed scientific, historical, or statistical research in the public interest that adheres to all other applicable ethics and privacy laws, when our deletion of the information is likely to render impossible or seriously impair the achievement of such research, provided we have obtained your informed consent;\n• Enable solely internal uses that are reasonably aligned with your expectations based on your relationship with us;\n• Comply with an existing legal obligation; or\n• Otherwise use your personal information, internally, in a lawful manner that is\ncompatible with the context in which you provided the information.\nChildren Under Thirteen\nPaavya does not knowingly collect personally identifiable information from children under the age of thirteen. If you are under the age of thirteen, you must ask your parent or guardian for permission to use this application.\n\nE-mail Communications\nFrom time to time, Paavya may contact you via email for the purpose of providing announcements, promotional offers, alerts, confirmations, surveys, and/or other general communication. In order to improve our Services, we may receive a notification when you open an email from Paavya or click on a link therein.\nIf you would like to stop receiving marketing or promotional communications via email from Paavya, you may opt out of such communications by unsubscribing at the bottom of the email account.\n\nChanges to this Statement\nPaavya reserves the right to change this Privacy Policy from time to time. We will notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your account, by placing a prominent notice on our application, and/or by updating any privacy information. Your continued use of the application and/or Services available after such modifications will constitute your: (a) acknowledgment of the modified Privacy Policy; and (b) agreement to abide and be bound by that Policy.\n\nContact Information\nPaavya welcomes your questions or comments regarding this Statement of Privacy. If you believe that Paavya has not adhered to this Statement, please contact Paavya at:\nPaavya LLC\n2090 Dunwoody Club Dr Atlanta, Georgia 30350\nEmail Address: info@paavya.com\nTelephone number: _________________\nEffective as of October 06, 2023',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'xnimucz1': {
      'en': 'Exit',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7clu22s6': {
      'en': 'Paavya Privacy Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gry42l0l': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Termsandconditions
  {
    'ypwmrtd0': {
      'en':
          'Agreement between User and www.paavya.com\nWelcome to www.paavya.com. The www.paavya.com website (the \"Site\") is comprised of various web pages operated by Paavya LLC (\"Paavya\"). www.paavya.com is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein (the \"Terms\"). Your use of www.paavya.com constitutes your agreement to all such Terms. Please read these terms carefully, and keep a copy of them for your reference.\nwww.paavya.com is a Financial technology Site.\nWe give users access to see their finances in a single view allowing them to control all of their finances in one tool\n\nPrivacy\nYour use of www.paavya.com is subject to Paavya\'s Privacy Policy. Please review our Privacy Policy, which also governs the Site and informs users of our data collection practices.\nElectronic Communications\nVisiting www.paavya.com or sending emails to Paavya constitutes electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures and other communications that we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communications be in writing.\n\nYour Account\nIf you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that Paavya is not responsible for third party access to your account that results from theft or misappropriation of your account. Paavya and its associates reserve the right to refuse or cancel service, terminate accounts, or remove or edit content in our sole discretion.\n\nChildren Under Thirteen\nPaavya does not knowingly collect, either online or offline, personal information from persons under the age of thirteen. If you are under 18, you may use www.paavya.com only with permission of a parent or guardian.\n\nCancellation/Refund Policy\nYou may cancel your subscription at any time. Any cancellations made after 60 days of service will not qualify for a refun. Please contact us at subscription@paavya.com with any questions.\n\nLinks to Third Party Sites/Third Party Services\nwww.paavya.com may contain links to other websites (\"Linked Sites\"). The Linked Sites are not under the control of Paavya and Paavya is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. Paavya is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Paavya of the site or any association with its operators.\n\nCertain services made available via www.paavya.com are delivered by third party sites and organizations. By using any product, service or functionality originating from the www.paavya.com domain, you hereby acknowledge and consent that Paavya may share such information and data with any third party with whom Paavya has a contractual relationship to provide the requested product, service or functionality on behalf of www.paavya.com users and customers.\nNo Unlawful or Prohibited Use/Intellectual Property\n\nYou are granted a non-exclusive, non-transferable, revocable license to access and use www.paavya.com strictly in accordance with these terms of use. As a condition of your use of the Site, you warrant to Paavya that you will not use the Site for any purpose that is unlawful or prohibited by these Terms. You may not use the Site in any manner which could damage, disable, overburden, or impair the Site or interfere with any other party\'s use and enjoyment of the Site. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Site.\n\nAll content included as part of the Service, such as text, graphics, logos, images, as well as the compilation thereof, and any software used on the Site, is the property of Paavya or its suppliers and protected by copyright and other laws that protect intellectual property and proprietary rights. You agree to observe and abide by all copyright and other proprietary notices, legends or other restrictions contained in any such content and will not make any changes thereto.\n\nYou will not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on the Site. Paavya content is not for resale. Your use of the Site does not entitle you to make any unauthorized use of any protected content, and in particular you will not delete or alter any proprietary rights or attribution notices in any content. You will use protected content solely for your personal use, and will make no other use of the content without the express written permission of Paavya and the copyright owner. You agree that you do not acquire any ownership rights in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of Paavya or our licensors except as expressly authorized by these Terms.\n\nThird Party Accounts\nYou will be able to connect your Paavya account to third party accounts. By connecting your Paavya account to your third party account, you acknowledge and agree that you are consenting to the continuous release of information about you to others (in accordance with your privacy settings on those third party sites). If you do not want information about you to be shared in this manner, do not use this feature.\nInternational Users\nThe Service is controlled, operated and administered by Paavya from our offices within the USA.\n\n\n If you access the Service from a location outside the USA, you are responsible for compliance with all local laws. You agree that you will not use the Paavya Content accessed through www.paavya.com in any country or in any manner prohibited by any applicable laws, restrictions or regulations.\nIndemnification\nYou agree to indemnify, defend and hold harmless Paavya, its officers, directors, employees, agents and third parties, for any losses, costs, liabilities and expenses (including reasonable attorney\'s fees) relating to or arising out of your use of or inability to use the Site or services, any user postings made by you, your violation of any terms of this Agreement or your violation of any rights of a third party, or your violation of any applicable laws, rules or regulations. Paavya reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Paavya in asserting any available defenses.\n\nArbitration\nIn the event the parties are not able to resolve any dispute between them arising out of or concerning these Terms and Conditions, or any provisions hereof, whether in contract, tort, or otherwise at law or in equity for damages or any other relief, then such dispute shall be resolved only by final and binding arbitration pursuant to the Federal Arbitration Act, conducted by a single neutral arbitrator and administered by the American Arbitration Association, or a similar arbitration service selected by the parties, in a location mutually agreed upon by the parties. The arbitrator\'s award shall be final, and judgment may be entered upon it in any court having jurisdiction. In the event that any legal or equitable action, proceeding or arbitration arises out of or concerns these Terms and Conditions, the prevailing party shall be entitled to recover its costs and reasonable attorney\'s fees. The parties agree to arbitrate all disputes and claims in regards to these Terms and Conditions or any disputes arising as a result of these Terms and Conditions, whether directly or indirectly, including Tort claims that are a result of these Terms and Conditions. The parties agree that the Federal Arbitration Act governs the interpretation and enforcement of this provision. The entire dispute, including the scope and enforceability of this arbitration provision shall be determined by the Arbitrator. This arbitration provision shall survive the termination of these Terms and Conditions.\n\nClass Action Waiver\nAny arbitration under these Terms and Conditions will take place on an individual basis; class arbitrations and class/representative/collective actions are not permitted. THE PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN EACH\'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE AND/ OR REPRESENTATIVE PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL ACTION AGAINST THE OTHER. Further, unless both you and Paavya agree otherwise, the arbitrator may not consolidate more than one person\'s claims, and may not otherwise preside over any form of a representative or class proceeding.\nLiability Disclaimer\n\n THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE SITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. PAAVYA LLC AND/OR ITS SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE SITE AT ANY TIME.\nPAAVYA LLC AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS CONTAINED ON THE SITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS ARE PROVIDED \"AS IS\" WITHOUT WARRANTY OR CONDITION OF ANY KIND. PAAVYA LLC AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.\nTO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PAAVYA LLC AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SITE, WITH THE DELAY OR INABILITY TO USE THE SITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF PAAVYA LLC OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE.\n\nTermination/Access Restriction\nPaavya reserves the right, in its sole discretion, to terminate your access to the Site and the related services or any portion thereof at any time, without notice. To the maximum extent permitted by law, this agreement is governed by the laws of the State of Georgia and you hereby consent to the exclusive jurisdiction and venue of courts in Georgia in all disputes arising out of or relating to the use of the Site. Use of the Site is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms, including, without limitation, this section.\n\nYou agree that no joint venture, partnership, employment, or agency relationship exists between you and Paavya as a result of this agreement or use of the Site. Paavya\'s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Paavya\'s right to comply with governmental, court and law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by Paavya with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect.\nUnless otherwise specified herein, this agreement constitutes the entire agreement between the user and Paavya with respect to the Site and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Paavya with respect to the Site. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be written in English.\n\nChanges to Terms\nPaavya reserves the right, in its sole discretion, to change the Terms under which www.paavya.com is offered. The most current version of the Terms will supersede all previous versions. Paavya encourages you to periodically review the Terms to stay informed of our updates.\n\nContact Us\nPaavya welcomes your questions or comments regarding the Terms:\nPaavya LLC\n2090 Dunwoody Club Dr Atlanta, Georgia 30350\nEmail Address: info@paavya.com\nTelephone number: _________________\nEffective as of October 06, 2023',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3nyks6xx': {
      'en': 'Exit',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'odlkcipw': {
      'en': 'Terms and Conditions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '35xyhgdw': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // dashboard_empty
  {
    'ppok3ff5': {
      'en': 'Welcome',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'i1h19a5m': {
      'en':
          'This is an overview of all your Paavya\n accounts. Start things up by adding an\naccount.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'yc2kx63n': {
      'en': 'Add your acount',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zbimwtls': {
      'en': 'Add accounts later',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    's5ugsftd': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // notifications
  {
    'ijg7jct8': {
      'en':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'y29rtgd5': {
      'en': 'Push Notifications',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ofugtlow': {
      'en':
          'Receive Push notifications from our application on a semi regular basis.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'v26o8tud': {
      'en': 'Email Notifications',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fgi6zyhr': {
      'en':
          'Receive email notifications from our marketing team about new features.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5hyni8fg': {
      'en': 'Balance Alerts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '65ks5nka': {
      'en': 'Allow us to send you alerts when your balance is running low.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b3hca7b0': {
      'en': 'Successful Transaction',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '366zxxjn': {
      'en':
          'Receive a notification when you are receiving or sending money successfully.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jxg1exp1': {
      'en': 'Spending Limits',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zopvxc0u': {
      'en':
          'Receive a notification when you reach your spending limit for your card budget.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'om8uwjwa': {
      'en': 'Change Changes',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ke84nfwu': {
      'en': 'Notifications',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'myysf22u': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // login
  {
    '0a1tanir': {
      'en': 'Welcome Back!',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qdemnqdm': {
      'en': 'Sign in to your account',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hu7amdrc': {
      'en': 'Email',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'vlhpsgth': {
      'en': 'enter your email address',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'k7jazem7': {
      'en': 'Password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fma81z7j': {
      'en': 'enter your password',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zkd797hx': {
      'en': 'Forgot Password?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'x75co5ry': {
      'en': 'LogIn',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ghdbipig': {
      'en':
          'Please use your biometrics to login for security to protect your data.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wo2sjrki': {
      'en': 'Don\'t have an account?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '0gaq9lpj': {
      'en': ' Sign Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rqldg521': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // topup
  {
    't9ety68w': {
      'en': 'How would you like to Top Up?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'r7wbcpn2': {
      'en': 'Credit/Debit Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'usjb2zv7': {
      'en': 'Credit/Debit Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bmt3p2cp': {
      'en': 'Top Up ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ljkhq0lw': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // bankDetails
  {
    'olk748ws': {
      'en': 'Bank Account',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z2beytfe': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // createGoal
  {
    '9ig1860z': {
      'en': 'Name',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qrhqkygy': {
      'en': 'create a new savings goal',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '82320uy3': {
      'en': 'Goal Amount',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wmptahh9': {
      'en': 'ex. 1450.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ok3yeoa0': {
      'en': 'Details',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'klnpck5f': {
      'en': 'add any details to this budget item',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '165wwj9q': {
      'en': 'Emergency ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'm9rjov43': {
      'en': 'Car Repairs',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zrolc18k': {
      'en': 'House Repair',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lsr0utd9': {
      'en': 'Buy Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'chkhc486': {
      'en': 'Other',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'mxk41yqz': {
      'en': 'Save',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '31bej71q': {
      'en': 'Create a New Goal',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ud47cfso': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // monthlyBudgets
  {
    '975y9jah': {
      'en': 'Monthly Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'w5cig2xk': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'yg2ex6bn': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'x2gpjwhn': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hjsbxfvt': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'idk9xzka': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'mctxar0r': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'vd869vx4': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '126wbytl': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '26dqk2dl': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1rgp4df2': {
      'en': 'Fast Food',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'x2fabaj5': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'z2v0nm0w': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'd9prvdai': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dv2kxews': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ge66551b': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qono277h': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7rfwnsqm': {
      'en': 'Retail Shopping',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qnppg9lr': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jn6yjzyu': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'tmpljptg': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9ztu0ryu': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'f8h3r1d5': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ix07rvtb': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'd6cto3nk': {
      'en': 'Groceries',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '04kv6r3t': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '672fu3xu': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '8021oe0p': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'aa0dubyw': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qq4s2fyh': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2inv6iol': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'w8z772e3': {
      'en': 'Other',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5pzhe1ew': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'yhytq3ye': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ifhi4rkd': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dmrdl121': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ogzf37l1': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2dtg3n42': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1fmnv104': {
      'en': 'Gasoline',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ledfrs8q': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'bzh40ago': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'eijubqv9': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'l4j0nvke': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'fdp23s3n': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ty8xql5t': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'el4jwpbv': {
      'en': 'Restaurants',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'js71bin8': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'aogv8y70': {
      'en': '/month',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'iroaysep': {
      'en': '\$750',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zpvufm14': {
      'en': ' left out of ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lwrd81xp': {
      'en': '\$1500',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'mzi1f6n2': {
      'en': '50%',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dg9hl7yl': {
      'en': 'Add New Budget Item',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4vgw9zez': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // aiiAyva
  {
    'h919xuy8': {
      'en': 'Ask Ayva something!',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4vi09rw5': {
      'en':
          'an AI assistant made by Paavya to support your financial questions.',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qvrrhjlb': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'm2pl57y9': {
      'en': 'paavya',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'zj0k2n52': {
      'en': 'Search',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'rq4lr6nc': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9mu5bc0t': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7izdxnph': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6z4t4kgl': {
      'en': 'Insights',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'cx66tirw': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9vlgh2e4': {
      'en': 'Ayva AI',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'vsghwi0w': {
      'en': 'View Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '5ooq156l': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // NavBar1
  {
    'sejvqdtg': {
      'en': 'Dashboard',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'pi2ztlh5': {
      'en': 'Budgets',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '02itrjia': {
      'en': 'Transactions',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wy1zeavb': {
      'en': 'My Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'akntj55l': {
      'en': 'Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // topup_new
  {
    'bn126egq': {
      'en': 'Top Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'sim46hj7': {
      'en': 'Balance',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hcubfs82': {
      'en': '\$413.81',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'f6ie7gf4': {
      'en': 'Select bank',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'e05i9yqo': {
      'en': 'Bank of America',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '244aeitl': {
      'en': 'Set amount',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '1tyg53xf': {
      'en': 'How much would you like to top up?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '86sfr6a7': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7xxhh3it': {
      'en': 'Top Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Card_confirm_topup
  {
    '1cic2wcp': {
      'en': 'You are sending',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2irmiph6': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wisj86p7': {
      'en': 'To',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jixgvs9y': {
      'en': 'Paavya Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'h88z4kcs': {
      'en': 'Go Back',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'to69ahdo': {
      'en': 'Confirm Top Up',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // recipient_of_transfer
  {
    'c4vcnwyz': {
      'en': 'Paavya Card',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hvkz2upr': {
      'en': '1234-5678-9012-3141',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // withdraw_new
  {
    '22gpdha9': {
      'en': 'Withdraw',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'jr8yed7c': {
      'en': 'Balance',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3vvo72p9': {
      'en': '\$413.81',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uq8nd60l': {
      'en': 'Set Amount',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '132ejwya': {
      'en': '\$10.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'uplf9zfy': {
      'en': '\$10.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qx9fe09h': {
      'en': '\$50.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'gbyyhpo9': {
      'en': '\$100.00',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'b2wynkg8': {
      'en': 'Withdraw',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // withdraw_badge
  {
    '1d8o13jy': {
      'en': 'Paypal',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // confirm_withdraw
  {
    '1wu0yg16': {
      'en': 'Verification',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ev7o12lc': {
      'en': 'Enter the 4-digits code to process your withdraw',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'wkbj5xfr': {
      'en': 'Didn\'t receive a code?',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '7rxa9jnk': {
      'en': 'Resend Code',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'kk0pg92t': {
      'en': 'Verify Withdraw',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // large_Card
  {
    'j9as88qh': {
      'en': 'Balance',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'c871b5ms': {
      'en': '\$7,630',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'dv4zfrn8': {
      'en': '**** 0149',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3wgdme74': {
      'en': '05/25',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '2jrvax08': {
      'en': 'CVV',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'urlt7mkz': {
      'en': '422',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // small_credit_card
  {
    'pd0zujvg': {
      'en': '5229-9012-3245-6789',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'hr66oq0e': {
      'en': 'Trey Banks',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '9ti5igsu': {
      'en': 'Exp ',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'znd5pypt': {
      'en': '11/25',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
  // Miscellaneous
  {
    '77ljc76y': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ye2ry734': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'tk95mf40': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'oz4bues5': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nzehu9vy': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '4qhp7imw': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ial06mrv': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '86y3bhox': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '09w8gdoa': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'p258vu0a': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '3s2axn53': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lzmtx5pl': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ea72tzj3': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ffb3v98o': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'cam5e96o': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'lm8y4lhx': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'no6mu5ta': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'qkmsf77z': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6118sz1w': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '6u32u4x8': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    's2ixizzg': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    '42riaz6r': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'nlmow9tc': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'ech8iezm': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
    'a45c4vcq': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ko': '',
    },
  },
].reduce((a, b) => a..addAll(b));
